import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import LeftSection from '@/widgets/left-section/LeftSection'
import Header from '@/widgets/header/Header'

const poppins = Poppins({
	subsets: ['latin'],
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
})

export const metadata: Metadata = {
	title: 'Dashboard',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={poppins.className}>
				<LeftSection />
				<div className="pl-[270px] max-xl:pl-0">
					<div className="max-w-7xl mx-auto px-16 py-10 flex flex-col gap-12 max-lg:px-7 max-lg:py-7 max-sm:px-3 max-sm:gap-5">
						<Header />
						{children}
					</div>
				</div>
			</body>
		</html>
	)
}
